apiVersion: v1
kind: Service
metadata:
  name: ops-app2
  namespace: ops-app2-eks-dev
  labels: # ← 줄바꿈
    app.kubernetes.io/name: ops-app2 # ← 들여쓰기 추가
spec:
  selector:
    app.kubernetes.io/name: ops-app2
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP
